# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0.xci
# IP: The module: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/bd_4a56.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56 || ORIG_REF_NAME==bd_4a56} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_4a56_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_r_sync_0 || ORIG_REF_NAME==bd_4a56_r_sync_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_4a56_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_rx_0 || ORIG_REF_NAME==bd_4a56_rx_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_4a56_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_phy_0 || ORIG_REF_NAME==bd_4a56_phy_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_4a56_vfb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_vfb_0_0 || ORIG_REF_NAME==bd_4a56_vfb_0_0} -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/bd_4a56_ooc.xdc

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0.xci
# IP: The module: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/bd_4a56.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56 || ORIG_REF_NAME==bd_4a56} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_4a56_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_r_sync_0 || ORIG_REF_NAME==bd_4a56_r_sync_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_4a56_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_rx_0 || ORIG_REF_NAME==bd_4a56_rx_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_4a56_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_phy_0 || ORIG_REF_NAME==bd_4a56_phy_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_4a56_vfb_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4a56_vfb_0_0 || ORIG_REF_NAME==bd_4a56_vfb_0_0} -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/bd_0/bd_4a56_ooc.xdc

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
