# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/pin.xdc

# Block Designs: bd/kv260_phigent_heimdallr/kv260_phigent_heimdallr.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr || ORIG_REF_NAME==kv260_phigent_heimdallr} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axis_data_fifo_cap_0/kv260_phigent_heimdallr_axis_data_fifo_cap_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axis_data_fifo_cap_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axis_data_fifo_cap_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axis_subset_converter_0_0/kv260_phigent_heimdallr_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axis_subset_converter_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_v_frmbuf_wr_0_0/kv260_phigent_heimdallr_v_frmbuf_wr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_v_frmbuf_wr_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_v_frmbuf_wr_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xlslice_0_0/kv260_phigent_heimdallr_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xlslice_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_xlslice_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axis_data_fifo_cap_1/kv260_phigent_heimdallr_axis_data_fifo_cap_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axis_data_fifo_cap_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_axis_data_fifo_cap_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axis_subset_converter_0_1/kv260_phigent_heimdallr_axis_subset_converter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axis_subset_converter_0_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_axis_subset_converter_0_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_v_frmbuf_wr_0_1/kv260_phigent_heimdallr_v_frmbuf_wr_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_v_frmbuf_wr_0_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_v_frmbuf_wr_0_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xlslice_0_1/kv260_phigent_heimdallr_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xlslice_0_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_xlslice_0_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_reg_slice_vmcu_0/kv260_phigent_heimdallr_axi_reg_slice_vmcu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_reg_slice_vmcu_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_reg_slice_vmcu_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_vcu_0_0/kv260_phigent_heimdallr_vcu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_vcu_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_vcu_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xlslice_0_2/kv260_phigent_heimdallr_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xlslice_0_2 || ORIG_REF_NAME==kv260_phigent_heimdallr_xlslice_0_2} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xbar_10/kv260_phigent_heimdallr_xbar_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xbar_10 || ORIG_REF_NAME==kv260_phigent_heimdallr_xbar_10} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_ic_vcu_dec_0/kv260_phigent_heimdallr_axi_ic_vcu_dec_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_ic_vcu_dec_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_ic_vcu_dec_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xbar_11/kv260_phigent_heimdallr_xbar_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xbar_11 || ORIG_REF_NAME==kv260_phigent_heimdallr_xbar_11} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_ic_vcu_enc_0/kv260_phigent_heimdallr_axi_ic_vcu_enc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_ic_vcu_enc_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_ic_vcu_enc_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xlconcat_0_0_0/kv260_phigent_heimdallr_xlconcat_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xlconcat_0_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_xlconcat_0_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xlconstant_0_0/kv260_phigent_heimdallr_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xlconstant_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_xlconstant_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xlslice_0_3/kv260_phigent_heimdallr_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xlslice_0_3 || ORIG_REF_NAME==kv260_phigent_heimdallr_xlslice_0_3} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_ic_accel_ctrl_0/kv260_phigent_heimdallr_axi_ic_accel_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_ic_accel_ctrl_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_ic_accel_ctrl_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xbar_6/kv260_phigent_heimdallr_xbar_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xbar_6 || ORIG_REF_NAME==kv260_phigent_heimdallr_xbar_6} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_ic_audio_mcu_0/kv260_phigent_heimdallr_axi_ic_audio_mcu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_ic_audio_mcu_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_ic_audio_mcu_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xbar_7/kv260_phigent_heimdallr_xbar_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xbar_7 || ORIG_REF_NAME==kv260_phigent_heimdallr_xbar_7} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_ic_capture_0/kv260_phigent_heimdallr_axi_ic_capture_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_ic_capture_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_ic_capture_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xbar_8/kv260_phigent_heimdallr_xbar_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xbar_8 || ORIG_REF_NAME==kv260_phigent_heimdallr_xbar_8} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_ic_ctrl_100_0/kv260_phigent_heimdallr_axi_ic_ctrl_100_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_ic_ctrl_100_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_ic_ctrl_100_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_xbar_9/kv260_phigent_heimdallr_xbar_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_xbar_9 || ORIG_REF_NAME==kv260_phigent_heimdallr_xbar_9} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_axi_ic_ctrl_300_0/kv260_phigent_heimdallr_axi_ic_ctrl_300_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_axi_ic_ctrl_300_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_axi_ic_ctrl_300_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_PS_0_0/kv260_phigent_heimdallr_PS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_PS_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_PS_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_clk_wiz_0_0/kv260_phigent_heimdallr_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_clk_wiz_0_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_clk_wiz_0_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_proc_sys_reset_100MHz_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_proc_sys_reset_100MHz_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_300MHz_0/kv260_phigent_heimdallr_proc_sys_reset_300MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_proc_sys_reset_300MHz_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_proc_sys_reset_300MHz_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_600MHz_0/kv260_phigent_heimdallr_proc_sys_reset_600MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_proc_sys_reset_600MHz_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_proc_sys_reset_600MHz_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_regslice_34/kv260_phigent_heimdallr_s00_regslice_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_regslice_34 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_regslice_34} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_16/kv260_phigent_heimdallr_s01_regslice_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s01_regslice_16 || ORIG_REF_NAME==kv260_phigent_heimdallr_s01_regslice_16} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_m00_regslice_16/kv260_phigent_heimdallr_m00_regslice_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_m00_regslice_16 || ORIG_REF_NAME==kv260_phigent_heimdallr_m00_regslice_16} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_mmu_0/kv260_phigent_heimdallr_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_mmu_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_mmu_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_mmu_0/kv260_phigent_heimdallr_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s01_mmu_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_s01_mmu_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_regslice_35/kv260_phigent_heimdallr_s00_regslice_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_regslice_35 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_regslice_35} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_17/kv260_phigent_heimdallr_s01_regslice_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s01_regslice_17 || ORIG_REF_NAME==kv260_phigent_heimdallr_s01_regslice_17} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_m00_regslice_17/kv260_phigent_heimdallr_m00_regslice_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_m00_regslice_17 || ORIG_REF_NAME==kv260_phigent_heimdallr_m00_regslice_17} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_mmu_1/kv260_phigent_heimdallr_s00_mmu_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_mmu_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_mmu_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_mmu_1/kv260_phigent_heimdallr_s01_mmu_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s01_mmu_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_s01_mmu_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_regslice_30/kv260_phigent_heimdallr_s00_regslice_30.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_regslice_30 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_regslice_30} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_regslice_31/kv260_phigent_heimdallr_s00_regslice_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_regslice_31 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_regslice_31} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_auto_us_0/kv260_phigent_heimdallr_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_auto_us_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_auto_us_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_15/kv260_phigent_heimdallr_s01_regslice_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s01_regslice_15 || ORIG_REF_NAME==kv260_phigent_heimdallr_s01_regslice_15} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_auto_us_1/kv260_phigent_heimdallr_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_auto_us_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_auto_us_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s02_regslice_0/kv260_phigent_heimdallr_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s02_regslice_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_s02_regslice_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_auto_us_2/kv260_phigent_heimdallr_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_auto_us_2 || ORIG_REF_NAME==kv260_phigent_heimdallr_auto_us_2} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_m00_regslice_15/kv260_phigent_heimdallr_m00_regslice_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_m00_regslice_15 || ORIG_REF_NAME==kv260_phigent_heimdallr_m00_regslice_15} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_mmu_2/kv260_phigent_heimdallr_s00_mmu_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_mmu_2 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_mmu_2} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_regslice_32/kv260_phigent_heimdallr_s00_regslice_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_regslice_32 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_regslice_32} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_mmu_3/kv260_phigent_heimdallr_s00_mmu_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_mmu_3 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_mmu_3} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_mmu_2/kv260_phigent_heimdallr_s01_mmu_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s01_mmu_2 || ORIG_REF_NAME==kv260_phigent_heimdallr_s01_mmu_2} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s00_regslice_33/kv260_phigent_heimdallr_s00_regslice_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_s00_regslice_33 || ORIG_REF_NAME==kv260_phigent_heimdallr_s00_regslice_33} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_auto_pc_0/kv260_phigent_heimdallr_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_auto_pc_0 || ORIG_REF_NAME==kv260_phigent_heimdallr_auto_pc_0} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_auto_pc_1/kv260_phigent_heimdallr_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_auto_pc_1 || ORIG_REF_NAME==kv260_phigent_heimdallr_auto_pc_1} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_auto_pc_2/kv260_phigent_heimdallr_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_auto_pc_2 || ORIG_REF_NAME==kv260_phigent_heimdallr_auto_pc_2} -quiet] -quiet

# IP: bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_auto_pc_3/kv260_phigent_heimdallr_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_phigent_heimdallr_auto_pc_3 || ORIG_REF_NAME==kv260_phigent_heimdallr_auto_pc_3} -quiet] -quiet

# XDC: /workspace/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/kv260_phigent_heimdallr_ooc.xdc
