# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /workspace/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_15/kv260_phigent_heimdallr_s01_regslice_15.xci
# IP: The module: 'kv260_phigent_heimdallr_s01_regslice_15' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /workspace/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_15/kv260_phigent_heimdallr_s01_regslice_15_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_s01_regslice_15'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /workspace/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_15/kv260_phigent_heimdallr_s01_regslice_15_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_s01_regslice_15'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /workspace/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_15/kv260_phigent_heimdallr_s01_regslice_15.xci
# IP: The module: 'kv260_phigent_heimdallr_s01_regslice_15' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /workspace/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_15/kv260_phigent_heimdallr_s01_regslice_15_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_s01_regslice_15'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /workspace/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_s01_regslice_15/kv260_phigent_heimdallr_s01_regslice_15_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_s01_regslice_15'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
