# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/bd_8a97.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97 || ORIG_REF_NAME==bd_8a97} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_8a97_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_r_sync_0 || ORIG_REF_NAME==bd_8a97_r_sync_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_8a97_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_rx_0 || ORIG_REF_NAME==bd_8a97_rx_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_8a97_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_phy_0 || ORIG_REF_NAME==bd_8a97_phy_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_8a97_vfb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_vfb_0_0 || ORIG_REF_NAME==bd_8a97_vfb_0_0} -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/bd_8a97_ooc.xdc

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/bd_8a97.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97 || ORIG_REF_NAME==bd_8a97} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_8a97_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_r_sync_0 || ORIG_REF_NAME==bd_8a97_r_sync_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_8a97_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_rx_0 || ORIG_REF_NAME==bd_8a97_rx_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_8a97_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_phy_0 || ORIG_REF_NAME==bd_8a97_phy_0} -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_8a97_vfb_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_vfb_0_0 || ORIG_REF_NAME==bd_8a97_vfb_0_0} -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/bd_8a97_ooc.xdc

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
