# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0.xci
# IP: The module: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.srcs/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0.xci
# IP: The module: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0/kv260_phigent_heimdallr_proc_sys_reset_100MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_phigent_heimdallr_proc_sys_reset_100MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
