# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/ip_0/bd_8a97_vfb_0_0_axis_converter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_8a97_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_8a97_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8a97_vfb_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/ip_0/bd_8a97_vfb_0_0_axis_converter.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8a97_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_8a97_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/liyunzhi/phigent_new/kv260_phigent_heimdallr/prj/prj.gen/sources_1/bd/kv260_phigent_heimdallr/ip/kv260_phigent_heimdallr_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_8a97_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8a97_vfb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
